// keyChineseMap.ts

export const keyChineseMap = {}

// export const keyChineseMap = {
//   // ============ 常见通用字段 ============
//   id: 'ID编号',
//   name: '名称',
//   title: '标题',
//   content: '内容',
//   description: '描述',
//   subtitle: '副标题',
//   subheading: '小标题/二级标题',
//   show: '是否展示',
//   icon: '图标',
//   linkUrl: '链接地址',
//   fileUrl: '文件地址',
//   image: '图片',
//   buttonText: '按钮文本',
//   items: '项目列表',
//   features: '功能列表',
//   available: '可用',
//   detailsUrl: '详情链接',
//   detailsButtonText: '详情按钮文本',
//   date: '日期',
//   address: '地址',
//   phoneNumber: '电话号码',
//   createTime: '创建时间',
//   className: '样式类名',
//   occupation: '职业/身份',
//   time: '时间',
//   link: '链接',
//   video: '视频',
//   text: '文本',
//   team: '团队',
//   teamMember: '队员',
//   testimonial: '评价',
//   duration: '为期',
//   role: '角色',
//   key: "键",      
//   // ============ 业务相关（页面 / 区块） ============
//   pageTitle: '页面标题',
//   pageTitleEn: '页面英文标题',
//   metaKeywords: 'Meta关键词',
//   metaDescription: 'Meta描述',
//   metaTitle: 'Meta标题',
//   sectionTitle: '区块标题',
//   sectionSubtitle: '区块副标题',
//   sectionDescription: '区块说明',
//   sectionTagline: '区块标语',
//   heading: '大标题',
//   headingLarge: '大号主标题',
//   headingSmall: '小号主标题',
//   // ============ 业务中出现的区块命名 ============
//   contents: '内容',
//   footerText: '页脚文本',
//   headerText: '头部文本',
//   layoutLinks: '布局链接',
//   additionalInfo: '附加信息',
//   contactInfo: '联系信息',
//   introMessages: '介绍信息列表',
//   registerMessage: '注册提示信息',
//   copyright: '版权声明',
//   // ============ 图文 / 媒体 ============
//   logoUrl: 'Logo链接',
//   faviconUrl: 'Favicon链接',
//   mpQrcodeUrl: '公众号二维码',
//   zsxqQrcodeUrl: '知识星球二维码',
//   wechatQrcodeUrl: '微信二维码',
//   workWechatQrcodeUrl: '企业微信二维码',
//   coverUrl: '封面链接',
//   cover: '封面',
//   bg: '背景图',
//   // ============ 常见业务模块 ============
//   faqSection: '常见问答区块',
//   faqs: '常见问答列表',
//   aboutSection: '关于我们区块',
//   helpTitle: '帮助标题',
//   helpContent1: '帮助内容1',
//   helpContent2: '帮助内容2',
//   aboutText: '关于链接文本',
//   aboutImage1: '关于图片1',
//   aboutImage2: '关于图片2',
//   aboutVideo1: '关于视频1',
//   aboutShapeImage: '关于形状图片',
//   experienceYearsText: '经验年限文案',
//   pricingSection: '价格方案区块',
//   plans: '方案列表',
//   price: '价格',
//   priceUnit: '价格单位',
//   partnersSection: '合作伙伴区块',
//   partners: '合作伙伴列表',
//   expertiseSection: '专长区块',
//   expertise: '专长列表',
//   heroSliderSection: '轮播区块',
//   slides: '轮播列表',
//   testimonialsSection: '客户评价区块',
//   testimonials: '客户评价列表',
//   whatWeOfferSection: '我们提供的服务区块',
//   offer: '服务项列表',
//   showLanguageSelector: '是否显示语言选择',
//   // ============ branding / video / blocks ============
//   brandingSection: '品牌区块',
//   brandingImages: '品牌图片组',
//   blocks: '内容块',
//   videoSection: '视频区块',
//   // ============ business / team / process ============
//   businessSection: '业务区块',
//   teamSection: '团队区块',
//   // ============ 其他 ============
//   phone: '电话',
//   emails: '邮箱列表',
//   zipCode: '邮编',
//   formTitle: '表单标题',
//   // ============ Health Plans / Services 专用 ============
//   serviceDetailSection: '服务详情区块',
//   services: '服务列表',
//   // ============ Pricing Plans ============
//   pricingPlansSection: '定价套餐区块',
//   // ============ Subscribe / Blog / Specialties ============
//   subscribeSection: '订阅区块',
//   blogPostsSection: '博客文章区块',
//   ourSpecialtiesSection: '我们的专长区块',
//   listLeft: '左侧列表',
//   listRight: '右侧列表',
//   // ============ Banner / Diet / Testimonial 等区域 ============
//   bannerBottomArea: '底部横幅区域',
//   testimonialSection: '客户评价区块',
//   // ============ FAQ ============
//   faq: '常见问题列表',
//   // ============ Privacy / Terms ============
//   privacyContent: '隐私政策内容',
//   termsOfUse: '使用条款内容',
//   // ============ 其它可能出现的分段命名(示例) ============
//   section1: '分区1',
//   section2: '分区2',
//   section3: '分区3',
//   section4: '分区4',
//   section5: '分区5',
//   section6: '分区6',
//   section7: '分区7',
//   section8: '分区8',
//   section9: '分区9',
//   section10: '分区10',
  
//   offer1: '服务项1',
//   offer2: '服务项2',
//   offer3: '服务项3',
//   offer4: '服务项4',
//   offer5: '服务项5',
//   offer6: '服务项6',
//   offer7: '服务项7',
//   offer8: '服务项8',
//   offer9: '服务项9',
//   offer10: '服务项10',
  
//   process1: '流程1',
//   process2: '流程2',
//   process3: '流程3',
//   process4: '流程4',
//   process5: '流程5',
//   process6: '流程6',
//   process7: '流程7',
//   process8: '流程8',
//   process9: '流程9',
//   process10: '流程10',
  
//   plan1: '方案1',
//   plan2: '方案2',
//   plan3: '方案3',
//   plan4: '方案4',
//   plan5: '方案5',
//   plan6: '方案6',
//   plan7: '方案7',
//   plan8: '方案8',
//   plan9: '方案9',
//   plan10: '方案10',
  
//   feature1: '功能1',
//   feature2: '功能2',
//   feature3: '功能3',
//   feature4: '功能4',
//   feature5: '功能5',
//   feature6: '功能6',
//   feature7: '功能7',
//   feature8: '功能8',
//   feature9: '功能9',
//   feature10: '功能10',
  
//   counter1: '计数器1',
//   counter2: '计数器2',
//   counter3: '计数器3',
//   counter4: '计数器4',
//   counter5: '计数器5',
//   counter6: '计数器6',
//   counter7: '计数器7',
//   counter8: '计数器8',
//   counter9: '计数器9',
//   counter10: '计数器10',
  
//   service1: '服务1',
//   service2: '服务2',
//   service3: '服务3',
//   service4: '服务4',
//   service5: '服务5',
//   service6: '服务6',
//   service7: '服务7',
//   service8: '服务8',
//   service9: '服务9',
//   service10: '服务10',
  
//   btn1: '按钮1',
//   btn2: '按钮2',
//   btn3: '按钮3',
//   btn4: '按钮4',
//   btn5: '按钮5',
//   btn6: '按钮6',
//   btn7: '按钮7',
//   btn8: '按钮8',
//   btn9: '按钮9',
//   btn10: '按钮10',
  
//   title1: '标题1',
//   title2: '标题2',
//   title3: '标题3',
//   title4: '标题4',
//   title5: '标题5',
//   title6: '标题6',
//   title7: '标题7',
//   title8: '标题8',
//   title9: '标题9',
//   title10: '标题10',
  
//   slide1: '幻灯片1',
//   slide2: '幻灯片2',
//   slide3: '幻灯片3',
//   slide4: '幻灯片4',
//   slide5: '幻灯片5',
//   slide6: '幻灯片6',
//   slide7: '幻灯片7',
//   slide8: '幻灯片8',
//   slide9: '幻灯片9',
//   slide10: '幻灯片10',

//   image1: "图片1",
//   image2: "图片2",
//   image3: "图片3",
//   image4: "图片4",
//   image5: "图片5",
//   image6: "图片6",
//   image7: "图片7",
//   image8: "图片8",
//   image9: "图片9",
//   image10: "图片10",

//   subtitle1: "副标题1",
//   subtitle2: "副标题2",
//   subtitle3: "副标题3",

//   testimonial1: "评价1",
//   testimonial2: "评价2",
//   testimonial3: "评价3",
//   testimonial4: "评价4",
//   testimonial5: "评价5",
//   // ============ 文章/图文结构 ============
//   additionalSection: '附加区块',
//   content1: '正文内容1',
//   content2: '正文内容2',
//   projectDetailSection: '项目详细区块',
//   // ============ 其他字段补充 ============
//   postalCode: '邮政编码',
//   code: '编码',
//   phone_number: '电话(下划线原字段，仅示例)',
//   // ============ 仅示例：可自行补充更多（重复或多余字段省略） ============
  
//   aboutusSection: '关于我们部分',
//   visionSection: '愿景部分',
//   paragraph: '段落',
//   paragraph1: '段落1',
//   paragraph2: '段落2',
//   mainImage: '主图',
//   mainTitle: '主标题',
//   aboutImage: '关于图片',
//   experienceText: '经验文本',
//   missionSection: '使命部分',
//   clientSection: '客户部分',
//   servicesSection: '服务部分',
//   reviews: '评论',
//   welcome: '欢迎语',
//   highlightText: '高亮文本',
//   sliderSection: '轮播部分',
//   strategySection: '策略部分',
//   introduceSection: '介绍部分',
//   clientCaseSection: '客户案例部分',
//   ourServicesSection: '我们的服务部分',
//   servicesProcessSection: '服务流程部分',
//   steps: '步骤',
//   newsSection: '新闻部分',
//   recipeSection: '食谱部分',
//   featureListLeft: '功能列表左',
//   featureListRight: '功能列表右',
//   dietPlanSection: '饮食计划部分',
//   meals: '膳食',
//   day: '天',
//   days: '每一天',
//   process: '流程',
//   details: '细节',
//   nameNumber: '流程名称编号',
//   delay: '延迟',
//   value: '值',
//   suffix: '后缀',
//   btn: '按钮',

//   videoUrl: "视频URL",
//   heroSection: "顶部区块",
//   status: "状态列表",
//   heroImages: "顶部图组",
//   dark: "暗色图",
//   light: "亮色图",
//   heroTitle1: "顶部标题1",
//   heroTitle2: "顶部标题2",
//   skillsSlider: "技能滑块列表",
//   heroParagraph1: "顶部段落1",
//   heroParagraph2: "顶部段落2",
//   heroParagraph3: "顶部段落3",

//   tags: "标签数组",

//   resumeSection: "履历区块",
//   education: "教育经历数组",
//   degree: "学位",
//   institution: "机构",
//   experience: "工作经历数组",
//   resumeParagraph: "履历段落",
//   titleEducation1: "教育标题1",
//   titleEducation2: "教育标题2",
//   titleExperience1: "经历标题1",
//   titleExperience2: "经历标题2",
//   educationParagraph: "教育段落",

//   contactSection: "联系区块",
//   contactData: "联系数据数组",

//   serviceSection: "服务区块",
//   sidebarProfile: "侧边栏个人资料",
//   age: "年龄",
//   city: "城市",
//   avatar: "头像",
//   skills: "技能数组",
//   percentage: "百分比",
//   communitySection: "社区区块",

//   advantagesSection: "优势区块",
//   advantages: "优势列表",

//   avatarUrl: "头像链接",
//   starsHtml: "星级HTML",

//   healthCasesSection: "健康案例区块",
    
// }

